apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30020
      port: 8080
      targetPort: 8080
  selector:
    app: api-gateway