sudo: required

services:
  - docker

before_install:
  - docker build -t davidainslie/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run davidainslie/react-test npm test -- --coverage

after_success:
  - docker build -t davidainslie/multi-client ./client
  - docker build -t davidainslie/multi-nginx ./nginx
  - docker build -t davidainslie/multi-api ./api
  - docker build -t davidainslie/multi-worker ./worker

  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take these images and push them to dockerhub
  - docker push davidainslie/multi-client
  - docker push davidainslie/multi-nginx
  - docker push davidainslie/multi-api
  - docker push davidainslie/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-890953945913"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY