apiVersion: v1
kind: Pod
metadata:
  name: hello-nodejs
  labels:
    app: hello-nodejs
spec:
  containers:
    - name: hello-nodejs
      image: davidainslie/hello-nodejs
      ports:
        - name: app-port
          containerPort: 3000