apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-nodejs-controller
spec:
  replicas: 2
  selector:
    app: hello-nodejs
  template:
    metadata:
      labels:
        app: hello-nodejs
    spec:
      containers:
        - name: hello-nodejs
          image: davidainslie/hello-nodejs
          ports:
            - name: app-port
              containerPort: 3000