apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.11
      ports:
        - containerPort: 80
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
      resources:
        limits:
          memory: 256Mi
          cpu: 250m    
    - name: webapp
      image: davidainslie/hello-nodejs
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: 256Mi
          cpu: 250m  
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
        items:
          - key: reverse-proxy.conf
            path: reverse-proxy.conf
