apiVersion: v1
kind: Service
metadata:
  name: app-3-service
spec:
  selector:
    app: app-3
  type: NodePort
  ports:
    - port: 31001
      nodePort: 31001
      targetPort: http-port
      protocol: TCP