apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort  
  ports:
    - nodePort: 31756
      port: 80
      protocol: TCP
      targetPort: 80 