apiVersion: v1
kind: Service
metadata:
  name: app-1-service
spec:
  selector:
    app: app-1
  type: NodePort
  ports:
    - port: 80
      # nodePort: 31001 <- Optional - one can be automatically provided
      targetPort: app-port
      protocol: TCP