apiVersion: v1
kind: ReplicationController
metadata:
  name: app-1
spec:
  replicas: 2
  selector:
    app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: app-1
          image: davidainslie/hello-nodejs
          ports:
            - name: app-port
              containerPort: 3000