version: "3.3"

services:
  db:
    image: orchardup/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: mysecurepass

  web:
    build: .
    command: node index-db.js
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: mysecurepass
      MYSQL_HOST: db