apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-aws-ebs            # Users request a particular Storage class - So the name of the StorageClass is significant
provisioner: kubernetes.io/aws-ebs  # Provisioner determines the volume plugin used for provisioning PVs
parameters:
  type: gp2                         # General purpose SSD backed Volume Type in AWS EBS - Refer: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html
reclaimPolicy: Delete               # Set to either Delete (default) or Retain.
                                    # Persisent Volumes created using this storage class will have this reclaim policy 