apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: davidainslie/multi-worker
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: 256Mi
          cpu: 250m