apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-webapp
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    # Load balance traffic across Pods matching this label selector
    app: webapp